/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
        dark: 'var(--color-dark)',
        black: 'var(--color-black)',
        'black-2': 'var(--color-black-2)',
        'kelly-green': 'var(--kelly-green)',
        'pakistan-green': 'var(--pakistan-green)',
        'yellow-green': 'var(--yellow-green)',
        'gray-50': 'var(--color-gray-50)',
        'gray-100': 'var(--color-gray-100)',
        'gray-500': 'var(--color-gray-500)',
        'gray-600': 'var(--color-gray-600)',
        'gray-700': 'var(--color-gray-700)',
        'white': 'var(--color-white)'
      },
      fontFamily: {
        sans: [
          'Wix Madefor Text',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"Noto Sans"',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        display: [
          'Wix Madefor Display',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"Noto Sans"',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', '"Liberation Mono"', '"Courier New"', 'monospace'],
      },
      backgroundImage: {
        'gradient-top': 'var(--gradient-top)',
        'gradient-right': 'var(--gradient-right)',
        'gradient-bottom': 'var(--gradient-bottom)',
        'gradient-left': 'var(--gradient-left)',
        'gradient-top-right': 'var(--gradient-top-right)',
        'gradient-bottom-right': 'var(--gradient-bottom-right)',
        'gradient-top-left': 'var(--gradient-top-left)',
        'gradient-bottom-left': 'var(--gradient-bottom-left)',
        'gradient-radial': 'var(--gradient-radial)'
      }
    },
  },
  plugins: [],
}
